### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by TomE8** [ankurhanda/VLP16DataReader#1]
hi,
how do I install this git to my ubunto?
Tom

**Comment by ankurhanda** [comment]
Hi Tom, 

Do you have pcl installed on your machine? Once you have installed PCL it is just about hooking pcl to the this and you should be able to run that on ubuntu.

Ankur.

**Comment by TomE8** [comment]
hi,
Thank you for your fast replay... 8-)
I want to make sure I have understood correctly what this git does:
It connects to the vlp 16 sensor and it reads it's the data (like the velo-view program?)
Can you explain more in detail what is the output: what format is it, and how it is organized?

**Comment by ankurhanda** [comment]
Yes, it reads the data from vlp 16 but it is a light-weight wrapper unlike veloview. For now I save the points in a txt file like this.

pointfile<<p.x<<", "<<p.y<<", "<<p.z<< std::endl;

**Comment by TomE8** [comment]
cool...
Referring to your previous qustion: I have install pcl. How should I now Install your program? what should I run and do in order to instll it? 
Thank you very much for your help,
Tom

**Comment by ankurhanda** [comment]
create a build directory and do 

cmake .. 
make -j8

that's all you should see an executable if everything goes OK.
